#!/bin/bash
# Links table cleanup script - runs deletions in batches for better performance

DB="/home/petegriffiths/code/go/src/browse/crawler.db"

echo "=== Links Table Cleanup ==="
echo "Before: $(sqlite3 "$DB" 'SELECT COUNT(*) FROM links') links"

# Function to delete and report
delete_pattern() {
    local desc="$1"
    local sql="$2"
    sqlite3 "$DB" "$sql"
    echo "✓ $desc"
}

echo ""
echo "Removing junk entries..."

# Special characters at start
delete_pattern "Phone numbers (+...)" "DELETE FROM links WHERE to_domain LIKE '+%'"
delete_pattern "Tel links" "DELETE FROM links WHERE to_domain LIKE 'tel:%'"
delete_pattern "Starts with !" "DELETE FROM links WHERE to_domain LIKE '!%'"
delete_pattern "Starts with $" "DELETE FROM links WHERE to_domain LIKE '\$%'"
delete_pattern "Starts with (" "DELETE FROM links WHERE to_domain LIKE '(%'"
delete_pattern "Starts with \"" "DELETE FROM links WHERE to_domain LIKE '\"%'"
delete_pattern "Starts with ." "DELETE FROM links WHERE to_domain LIKE '.%'"
delete_pattern "Starts with -" "DELETE FROM links WHERE to_domain LIKE '-%'"
delete_pattern "Starts with ," "DELETE FROM links WHERE to_domain LIKE ',%'"
delete_pattern "Starts with *" "DELETE FROM links WHERE to_domain LIKE '*%'"
delete_pattern "Starts with #" "DELETE FROM links WHERE to_domain LIKE '#%'"
delete_pattern "Starts with @" "DELETE FROM links WHERE to_domain LIKE '@%'"
delete_pattern "Starts with ?" "DELETE FROM links WHERE to_domain LIKE '?%'"
delete_pattern "Starts with /" "DELETE FROM links WHERE to_domain LIKE '/%'"
delete_pattern "Starts with {" "DELETE FROM links WHERE to_domain LIKE '{%'"
delete_pattern "Starts with [" "DELETE FROM links WHERE to_domain LIKE '[%'"

echo ""
echo "Removing invalid domains..."
delete_pattern "No dots" "DELETE FROM links WHERE to_domain NOT LIKE '%.%'"
delete_pattern "Too short (<4)" "DELETE FROM links WHERE LENGTH(to_domain) < 4"
delete_pattern "Too long (>80)" "DELETE FROM links WHERE LENGTH(to_domain) > 80"

echo ""
echo "Removing spam farms..."
delete_pattern "51dzw.com" "DELETE FROM links WHERE to_domain LIKE '%.51dzw.com'"
delete_pattern "sxwmcc.com" "DELETE FROM links WHERE to_domain LIKE '%.sxwmcc.com'"
delete_pattern "9856.cn" "DELETE FROM links WHERE to_domain LIKE '%.9856.cn'"

echo ""
echo "Removing blog platforms..."
delete_pattern "livejournal.com" "DELETE FROM links WHERE to_domain LIKE '%.livejournal.com'"
delete_pattern "dreamwidth.org" "DELETE FROM links WHERE to_domain LIKE '%.dreamwidth.org'"
delete_pattern "insanejournal.com" "DELETE FROM links WHERE to_domain LIKE '%.insanejournal.com'"
delete_pattern "greatestjournal.com" "DELETE FROM links WHERE to_domain LIKE '%.greatestjournal.com'"
delete_pattern "tumblr.com" "DELETE FROM links WHERE to_domain LIKE '%.tumblr.com'"
delete_pattern "blogspot (all TLDs)" "DELETE FROM links WHERE to_domain LIKE '%.blogspot.%'"
delete_pattern "wordpress.com" "DELETE FROM links WHERE to_domain LIKE '%.wordpress.com'"
delete_pattern "createblog.com" "DELETE FROM links WHERE to_domain LIKE '%.createblog.com'"
delete_pattern "beeplog" "DELETE FROM links WHERE to_domain LIKE '%.beeplog.%'"

echo ""
echo "Removing software download spam..."
delete_pattern "softonic" "DELETE FROM links WHERE to_domain LIKE '%.softonic.%'"
delete_pattern "uptodown" "DELETE FROM links WHERE to_domain LIKE '%.uptodown.%'"
delete_pattern "informer.com" "DELETE FROM links WHERE to_domain LIKE '%.informer.com'"

echo ""
echo "Removing other spam platforms..."
delete_pattern "sikatika.com" "DELETE FROM links WHERE to_domain LIKE '%.sikatika.com'"
delete_pattern "qowap.com" "DELETE FROM links WHERE to_domain LIKE '%.qowap.com'"
delete_pattern "listal.com" "DELETE FROM links WHERE to_domain LIKE '%.listal.com'"
delete_pattern "mykajabi.com" "DELETE FROM links WHERE to_domain LIKE '%.mykajabi.com'"
delete_pattern "stck.me" "DELETE FROM links WHERE to_domain LIKE '%.stck.me'"
delete_pattern "izrablog.com" "DELETE FROM links WHERE to_domain LIKE '%.izrablog.com'"
delete_pattern "blogsidea.com" "DELETE FROM links WHERE to_domain LIKE '%.blogsidea.com'"
delete_pattern "blogmazing.com" "DELETE FROM links WHERE to_domain LIKE '%.blogmazing.com'"
delete_pattern "jsyinshanfu.com" "DELETE FROM links WHERE to_domain LIKE '%.jsyinshanfu.com'"
delete_pattern "life3dblog.com" "DELETE FROM links WHERE to_domain LIKE '%.life3dblog.com'"

echo ""
echo "Removing social media..."
delete_pattern "facebook.com variants" "DELETE FROM links WHERE to_domain IN ('facebook.com','www.facebook.com','web.facebook.com','m.facebook.com')"
delete_pattern "twitter.com variants" "DELETE FROM links WHERE to_domain IN ('twitter.com','www.twitter.com','mobile.twitter.com','x.com','www.x.com')"
delete_pattern "instagram.com" "DELETE FROM links WHERE to_domain IN ('instagram.com','www.instagram.com')"
delete_pattern "linkedin.com" "DELETE FROM links WHERE to_domain IN ('linkedin.com','www.linkedin.com')"
delete_pattern "youtube.com" "DELETE FROM links WHERE to_domain IN ('youtube.com','www.youtube.com','m.youtube.com','youtu.be')"
delete_pattern "tiktok.com" "DELETE FROM links WHERE to_domain IN ('tiktok.com','www.tiktok.com')"
delete_pattern "pinterest.com" "DELETE FROM links WHERE to_domain IN ('pinterest.com','www.pinterest.com')"
delete_pattern "reddit.com" "DELETE FROM links WHERE to_domain IN ('reddit.com','www.reddit.com','old.reddit.com')"
delete_pattern "discord" "DELETE FROM links WHERE to_domain IN ('discord.com','discord.gg')"
delete_pattern "telegram" "DELETE FROM links WHERE to_domain IN ('telegram.org','t.me')"
delete_pattern "whatsapp" "DELETE FROM links WHERE to_domain IN ('whatsapp.com','api.whatsapp.com','wa.me')"

echo ""
echo "Removing big tech domains..."
delete_pattern "google" "DELETE FROM links WHERE to_domain LIKE '%.google.%' OR to_domain LIKE '%.googleapis.com' OR to_domain LIKE '%.gstatic.com'"
delete_pattern "apple.com" "DELETE FROM links WHERE to_domain LIKE '%.apple.com'"
delete_pattern "microsoft.com" "DELETE FROM links WHERE to_domain LIKE '%.microsoft.com'"
delete_pattern "amazon" "DELETE FROM links WHERE to_domain LIKE '%.amazon.%' OR to_domain LIKE '%.amazonaws.com' OR to_domain LIKE '%.cloudfront.net'"

echo ""
echo "Removing URL shorteners..."
delete_pattern "shorteners" "DELETE FROM links WHERE to_domain IN ('bit.ly','tinyurl.com','t.co','goo.gl','ow.ly','is.gd','buff.ly','j.mp','lnkd.in')"

echo ""
echo "Removing suspicious TLDs..."
delete_pattern ".click" "DELETE FROM links WHERE to_domain LIKE '%.click'"
delete_pattern ".top (spam)" "DELETE FROM links WHERE to_domain LIKE '%.top'"
delete_pattern ".loan" "DELETE FROM links WHERE to_domain LIKE '%.loan'"
delete_pattern ".work" "DELETE FROM links WHERE to_domain LIKE '%.work'"
delete_pattern ".gq/.ml/.cf/.tk/.ga" "DELETE FROM links WHERE to_domain LIKE '%.gq' OR to_domain LIKE '%.ml' OR to_domain LIKE '%.cf' OR to_domain LIKE '%.tk' OR to_domain LIKE '%.ga'"
delete_pattern ".pw" "DELETE FROM links WHERE to_domain LIKE '%.pw'"

echo ""
echo "Final cleanup..."
delete_pattern "Non-ASCII characters" "DELETE FROM links WHERE to_domain GLOB '*[^ -~]*'"

echo ""
echo "After: $(sqlite3 "$DB" 'SELECT COUNT(*) FROM links') links"

echo ""
echo "Vacuuming database..."
sqlite3 "$DB" "VACUUM"
echo "Done!"
